AllCops:
  TargetRubyVersion: 2.3
  Include:
    - '**/Capfile'
    - '**/config.ru'
    - '**/Guardfile'
    - '**/Rakefile'
  Exclude:
    - 'db/fixtures/**/*'
    - 'db/schema.rb'
    - 'test/fixtures/**/*'
    - 'vendor/**/*'
  DisplayCopNames: true
  DisplayStyleGuide: true

Rails:
  Enabled: true

#################### Style ####################

Style/AsciiComments:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false