---
development:
  cloud_name: hphuizsco
  api_key: '567735691454112'
  api_secret: Bjuc8l9bEJEWDa41rWHbCtASubM
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: hphuizsco
  api_key: '567735691454112'
  api_secret: Bjuc8l9bEJEWDa41rWHbCtASubM
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: hphuizsco
  api_key: '567735691454112'
  api_secret: Bjuc8l9bEJEWDa41rWHbCtASubM
  enhance_image_tag: true
  static_image_support: false
